name: github-action-learn
on: 
  push:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Set Up
              uses: actions/checkout@v4

            - name: Set Up Python
              uses: actions/setup-python@v5
              with:
                   python-version: '3.10' 
            - name: Runner
              run: python hello.py

            
